/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    'B&A': typeof import('./src/components/B&A.vue')['default']
    Breast: typeof import('./src/components/Breast.vue')['default']
    BreastAfterCare: typeof import('./src/components/BreastAfterCare.vue')['default']
    BreastDesign: typeof import('./src/components/BreastDesign.vue')['default']
    BreastPrecautions: typeof import('./src/components/BreastPrecautions.vue')['default']
    BreastQuestion: typeof import('./src/components/BreastQuestion.vue')['default']
    BreastSurgeryInfo: typeof import('./src/components/BreastSurgeryInfo.vue')['default']
    Eye1: typeof import('./src/components/eye/Eye1.vue')['default']
    Eye2: typeof import('./src/components/eye/Eye2.vue')['default']
    Eye3: typeof import('./src/components/eye/Eye3.vue')['default']
    Eye4: typeof import('./src/components/eye/Eye4.vue')['default']
    Eye5: typeof import('./src/components/eye/Eye5.vue')['default']
    Eye6: typeof import('./src/components/eye/Eye6.vue')['default']
    Face: typeof import('./src/components/Face.vue')['default']
    FaceLiftingChart: typeof import('./src/components/FaceLiftingChart.vue')['default']
    FaceLiftingTabs: typeof import('./src/components/FaceLiftingTabs.vue')['default']
    FacePrecautions: typeof import('./src/components/FacePrecautions.vue')['default']
    FaceQuestion: typeof import('./src/components/FaceQuestion.vue')['default']
    FaceSurgeryInfo: typeof import('./src/components/FaceSurgeryInfo.vue')['default']
    FAQ: typeof import('./src/components/FAQ.vue')['default']
    Fat: typeof import('./src/components/Fat.vue')['default']
    FatIs: typeof import('./src/components/FatIs.vue')['default']
    FatPrecautions: typeof import('./src/components/FatPrecautions.vue')['default']
    FatQuestion: typeof import('./src/components/FatQuestion.vue')['default']
    FatSurgeryInfo: typeof import('./src/components/FatSurgeryInfo.vue')['default']
    FatTarget: typeof import('./src/components/FatTarget.vue')['default']
    IncisionGuide: typeof import('./src/components/IncisionGuide.vue')['default']
    MentorInfo: typeof import('./src/components/MentorInfo.vue')['default']
    MentotPoint: typeof import('./src/components/MentotPoint.vue')['default']
    Nose1: typeof import('./src/components/Nose1.vue')['default']
    Nose2: typeof import('./src/components/Nose2.vue')['default']
    Nose3: typeof import('./src/components/Nose3.vue')['default']
    Nose4: typeof import('./src/components/Nose4.vue')['default']
    Nose5: typeof import('./src/components/Nose5.vue')['default']
    Nose6: typeof import('./src/components/Nose6.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePopup: typeof import('./src/components/SidePopup.vue')['default']
  }
}
